### ISSUE TITLE
Support for PowerBI?

### ISSUE THREAD

**Issue by phil-lgr** [microsoft/thematic#60]
There is no information on how this package is related to PowerBI, it would be helpful

**Comment by natoverse** [comment]
Hi,

If you use the [Thematic webapp](https://microsoft.github.io/thematic/) to create a theme, you can select the Power BI tab to see a set of color mappings for standard Power BI theme colors. You can download these as a JSON file that can be [imported to Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-report-themes#import-custom-report-theme-files). I'll add some documentation to the repo to make this more clear.

Thanks!
